Repository simple-robot/simbot-component-kook, pull requests merged in 2022-11, with the labels that each got.

#66 事件调度的异步性配置
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/BotStandardEventRegistrar.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentBotImpl.kt
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/KookBotConfiguration.kt
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/internal/KookBotImpl.kt
Labels: 特性

#67 重构bot实现内网络通讯逻辑
  buildSrc/src/main/kotlin/P.kt
  simbot-component-kook-boot/build.gradle.kts
  simbot-component-kook-boot/src/test/kotlin/forte/example/spring/app/SpringAppMain.kt
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/internal/KookBotImpl.kt
Labels: 特性

#65 修复事件调度中使用阻塞API导致卡死
  buildSrc/src/main/kotlin/P.kt
  buildSrc/src/main/kotlin/R.kt
  buildSrc/src/main/kotlin/simbot-kook-maven-publish.gradle.kts
  buildSrc/src/main/kotlin/simbot-kook-module-conventions.gradle.kts
  buildSrc/src/main/kotlin/simbot-kook-nexus-publish.gradle.kts
  libs.versions.toml
  simbot-component-kook-api/build.gradle.kts
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/KookApiRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/KookApiResult.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/event/Signal.kt
  simbot-component-kook-boot/build.gradle.kts
  simbot-component-kook-boot/src/test/kotlin/forte/example/spring/app/SpringAppMain.kt
  simbot-component-kook-boot/src/test/resources/application.yml
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookBotManager.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookChannel.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookComponentBot.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookContact.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookGuild.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookGuildMember.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookUserChat.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/BotStandardEventRegistrar.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookChannelImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentBotImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentGuildBotImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookGuildImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookGuildMemberImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookUserChatImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/event/KookMessageEventImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/KookBotConfiguration.kt
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/internal/KookBotImpl.kt
Labels: bug, 严重

#72 增加获取频道表情列表API
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/PageRequestParameters.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/guild/emoji/GuildEmojiListRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/guild/role/GuildRoleListRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/KMarkdown.kt
Labels: 特性

#73 试将子频道与私聊会话的消息发送机制变更为以KMarkdown为主；支持一次发送多条消息；修复`Card` 序列化结果格式错误的问题
  buildSrc/src/main/kotlin/P.kt
  libs.versions.toml
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/PageRequestParameters.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/guild/emoji/GuildEmojiListRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/guild/role/GuildRoleListRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/message/MessageCreateRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/message/MessageType.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Card.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/KMarkdown.kt
  simbot-component-kook-boot/build.gradle.kts
  simbot-component-kook-boot/src/test/kotlin/forte/example/spring/app/SpringAppMain.kt
  simbot-component-kook-boot/src/test/resources/application.yml
  simbot-component-kook-core/build.gradle.kts
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookChannelImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookUserChatImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookAtAllHere.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessageCreatedReceipt.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessagesTransformer.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookReceiveMessageContent.kt
Labels: 优化

#77 细化 `KookAttachmentMessage` 类型
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Attachments.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookAttachmentMessage.kt
Labels: 特性

#78 优化消息链解析
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/event/message/MessageEvents.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Card.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookChannelMessageDetailsContent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessagesTransformer.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookReceiveMessageContent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/util/RegexWalker.kt
Labels: 优化

#79 优化消息链解析等相关内容
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/message/MessageDetails.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/message/MessageDetailsImpl.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/event/message/MessageEvents.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Attachments.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Card.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookAttachmentMessage.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookChannelMessageDetailsContent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessageElement.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessagesTransformer.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookReceiveMessageContent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/util/RegexWalker.kt
Labels: ignore-in-release, 优化

#81 Release: v3.0.0.0-alpha.3
  .changelog/v3.0.0.0-alpha.3.md
  buildSrc/src/main/kotlin/P.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/message/MessageDetails.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/message/MessageDetailsImpl.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/event/message/MessageEvents.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Attachments.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Card.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/KookComponent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookAttachmentMessage.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookChannelMessageDetailsContent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessageCreatedReceipt.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessageElement.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessagesTransformer.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookReceiveMessageContent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/util/RegexWalker.kt
  simbot-component-kook-core/src/test/kotlin/example/MessageSerializerTest.kt
Labels: for-release
