Repository simple-robot/simbot-component-kook, pull requests merged in 2023-07, with the labels that each got.

#103 核心模块提供 `KookTempTarget` 支持追加临时消息id
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookChannelImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/event/KookMessageEventImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessagesTransformer.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookTempTarget.kt
  simbot-component-kook-core/src/test/resources/simbot-logger-slf4j.properties
Labels: 特性

#104 修复 /guild/view API 的数据解析问题以及 Bot 加入/离开 频道服务器时事件推送的问题
  .idea/compiler.xml
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/channel/ChannelViewRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/guild/GuildViewRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Channel.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/BotStandardEventRegistrar.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentBotImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentGuildBotImpl.kt
Labels: bug

#105 Release: v3.0.0.0-alpha.7
  .changelog/v3.0.0.0-alpha.7.md
  .idea/compiler.xml
  CHANGELOG.md
  buildSrc/src/main/kotlin/P.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/channel/ChannelViewRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/api/guild/GuildViewRequest.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/event/system/user/MessageBtnClickEvent.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/event/system/user/UserEvents.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Card.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/CardMessageBuilder.kt
  simbot-component-kook-api/src/main/kotlin/love/forte/simbot/kook/objects/Channel.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/event/KookMessageBtnClickEvent.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/BotStandardEventRegistrar.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookChannelImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentBotImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/KookComponentGuildBotImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/event/KookMessageBtnClickEventImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/internal/event/KookMessageEventImpl.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessages.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookMessagesTransformer.kt
  simbot-component-kook-core/src/main/kotlin/love/forte/simbot/component/kook/message/KookTempTarget.kt
  simbot-component-kook-core/src/test/resources/simbot-logger-slf4j.properties
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/KookBot.kt
  simbot-component-kook-stdlib/src/main/kotlin/love/forte/simbot/kook/internal/KookBotImpl.kt
  website/static/version.json
Labels: for-release
