Repository simple-robot/simbot-component-kook, pull requests merged in 2025-08, with the labels that each got.

#262 fix(core): 修复事件继承结构错误的问题
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/event/internal/KookMemberChangedEventImpl.kt
Labels: bug

#272 为 SendChannelMessageApi 增加 templateId 属性与相关的构建参数
  buildSrc/src/main/kotlin/P.kt
  simbot-component-kook-api/api/simbot-component-kook-api.api
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/api/message/SendChannelMessageApi.kt
Labels: API

#277 KookChannel 增加 DeleteSupport 支持
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/api/channel/DeleteChannelApi.kt
  simbot-component-kook-core/api/simbot-component-kook-core.api
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookChannel.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookCategoryChannelImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookChatChannelImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/Utils.kt
Labels: 特性

#280 让部分 boolean 类型字段的反序列化解析更宽松
  build.gradle.kts
  buildSrc/src/main/kotlin/P.kt
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/util/Serializers.kt
  simbot-component-kook-core/src/commonTest/kotlin/love/forte/simbot/component/event/GuildEventsDeserializeTests.kt
Labels: bug

#287 改进 ChannelKickoutApi 的部分相关测试
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/api/channel/ChannelKickoutApi.kt
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/objects/User.kt
  simbot-component-kook-api/src/commonTest/kotlin/love/forte/simbot/kook/api/channel/ChannelKickoutApiTest.kt
Labels: 优化

#291 增加 KookVoiceChannel 和 KookVoiceMember 等语音频道相关API支持
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/api/channel/ChannelKickoutApi.kt
  simbot-component-kook-api/src/commonMain/kotlin/love/forte/simbot/kook/api/channel/ChannelMoveUserApi.kt
  simbot-component-kook-api/src/commonTest/kotlin/love/forte/simbot/kook/api/channel/ChannelMoveUserApiTest.kt
  simbot-component-kook-core/api/simbot-component-kook-core.api
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookChannel.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookChatCapableChannel.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookChatChannel.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookGuild.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookVoiceChannel.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/KookVoiceMember.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/bot/internal/KookBotEvents.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/bot/internal/KookBotImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/event/internal/KookChannelChangedEventImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/event/internal/KookMemberChangedEventImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/event/internal/KookMessageEventImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/AbstractKookChatCapableChannelImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookCategoryChannelImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookChatChannelImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookGuildImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookVoiceChannelImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/KookVoiceMemberImpl.kt
  simbot-component-kook-core/src/commonMain/kotlin/love/forte/simbot/component/kook/internal/Utils.kt
Labels: 特性
